---
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Go generate
        run: go generate

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
      
      # - name: Prepare for GoReleaser
      #   run: |
      #     # Fuck goreleaser
      #     # git tag -f v0.0.0-$(git rev-parse --short HEAD)
      #     python3 -c 'import yaml'
      
      - name: Install cross-compiler for linux/arm64
        run: sudo apt-get update -q && sudo apt-get -y install gcc-aarch64-linux-gnu

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Upload assets
        uses: NyaMisty/upload-artifact-as-is@master
        with:
          path: dist/supervisord_*